import Link from "next/link";
import "./globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next js learnig",
    template: "%s | next js",
    absolute: "",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="w-full p-6 flex gap-8 justify-center bg-amber-200 text-center mb-6">
          <Link href={"/"}>home</Link>
          <Link href={"/about"}>about</Link>
          <Link href={"/dashboard"}>dashboard</Link>
          <Link href={"/contact"}>contact</Link>
        </header>
        {children}
        <footer className="w-full p-6 bg-amber-200 text-center mt-6">footer</footer>
      </body>
    </html>
  );
}
